### ISSUE TITLE
The project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [cda-tum/mqt-core#504]
### Environment information

FreeBSD 13.2
clang-16

### Description

You need to have ```install``` instructions in your cmake scripts.

### How to Reproduce

regular build/install

**Comment by burgholzer** [comment]
Thanks for raising this issue. This has been on our backlog for a while already.
We just saw no pressing need for these instructions as `mqt-core` is generally consumed as a submodule in all our other projects.
However, since the project is growing and becoming more independent, this makes more sense now.
Let me see how fast I can get a working set of instructions together.
